// RPL keyword data + context routing. Pure Node, no vscode dependency (testable).
// Verified against a live IOS XR device (vPE, CML) via `?` completion in
// (config-rpl) mode; gaps filled from Cisco IOS XR Routing Configuration Guide
// "Implementing Routing Policy" + Routing Command Reference "RPL Commands".

// [label, detail, insertSnippet?]  — insertSnippet uses VS Code snippet syntax.
const CONDITIONS = [
  ['destination in', 'destination in <prefix-set | (inline) | $param>', 'destination in ${1:prefix-set}'],
  ['destination longer-than', 'prefix-length greater than route prefix length', 'destination longer-than ${1:prefix-set}'],
  ['destination or-longer', 'prefix-length equal or greater than route prefix length', 'destination or-longer ${1:prefix-set}'],
  ['destination is-all', 'true for additional paths selected by all path-selection'],
  ['destination is-backup-path', 'true for backup path'],
  ['destination is-best-external', 'true for best external route'],
  ['destination is-best-path', 'true for best path'],
  ['destination is-multi-path', 'true for multiple paths'],
  ['destination is-multipath-protect', 'true for multipath-protect path'],
  ['destination-prefix in', 'flowspec: destination prefix in <prefix-set | (inline)>', 'destination-prefix in ${1:prefix-set}'],
  ['source-prefix in', 'flowspec: source prefix in <prefix-set | (inline)>', 'source-prefix in ${1:prefix-set}'],
  ['as-path in', 'as-path in <as-path-set | (ios-regex \'...\') | $param>', 'as-path in ${1:as-path-set}'],
  ['as-path is-local', 'true if path was originated locally'],
  ['as-path length', 'as-path length <eq|is|ge|le> <number>', 'as-path length ${1|eq,ge,le,is|} ${2:number}'],
  ['as-path unique-length', 'as-path unique-length <eq|is|ge|le> <number>', 'as-path unique-length ${1|eq,ge,le,is|} ${2:number}'],
  ['as-path neighbor-is', "as-path neighbor-is '<asn> [asn...]'", "as-path neighbor-is '${1:asn}'"],
  ['as-path originates-from', "as-path originates-from '<asn>'", "as-path originates-from '${1:asn}'"],
  ['as-path passes-through', "as-path passes-through '<asn>'", "as-path passes-through '${1:asn}'"],
  ['community matches-any', 'true if any community matches any set element', 'community matches-any ${1:community-set}'],
  ['community matches-every', 'true if every set element is matched', 'community matches-every ${1:community-set}'],
  ['community matches-within', 'true if every community matches the set', 'community matches-within ${1:community-set}'],
  ['community in', 'match based on match option present within the set', 'community in ${1:community-set}'],
  ['community is-empty', 'true if route has no community attribute'],
  ['community length', 'community length <eq|is|ge|le> <number>', 'community length ${1|eq,ge,le,is|} ${2:number}'],
  ['large-community matches-any', 'large-community matches-any <set | (inline)>', 'large-community matches-any ${1:set}'],
  ['large-community matches-every', 'large-community matches-every <set | (inline)>', 'large-community matches-every ${1:set}'],
  ['large-community matches-within', 'large-community matches-within <set | (inline)>', 'large-community matches-within ${1:set}'],
  ['large-community is-empty', 'true if route has no large-community attribute'],
  ['large-community length', 'large-community length <eq|is|ge|le> <number>', 'large-community length ${1|eq,ge,le,is|} ${2:number}'],
  ['extcommunity rt matches-any', 'extcommunity rt matches-any <set | (inline)>', 'extcommunity rt matches-any ${1:set}'],
  ['extcommunity rt matches-every', 'extcommunity rt matches-every <set | (inline)>', 'extcommunity rt matches-every ${1:set}'],
  ['extcommunity rt matches-within', 'extcommunity rt matches-within <set | (inline)>', 'extcommunity rt matches-within ${1:set}'],
  ['extcommunity rt in', 'extcommunity rt in <rt-set>', 'extcommunity rt in ${1:set}'],
  ['extcommunity rt is-empty', 'true if route has no RT extended community'],
  ['extcommunity soo matches-any', 'extcommunity soo matches-any <set | (inline)>', 'extcommunity soo matches-any ${1:set}'],
  ['extcommunity soo matches-every', 'extcommunity soo matches-every <set | (inline)>', 'extcommunity soo matches-every ${1:set}'],
  ['extcommunity soo matches-within', 'extcommunity soo matches-within <set | (inline)>', 'extcommunity soo matches-within ${1:set}'],
  ['extcommunity soo is-empty', 'true if route has no SoO extended community'],
  ['extcommunity color matches-any', 'extcommunity color matches-any <set | (inline)>', 'extcommunity color matches-any ${1:set}'],
  ['extcommunity color matches-every', 'extcommunity color matches-every <set | (inline)>', 'extcommunity color matches-every ${1:set}'],
  ['extcommunity color matches-within', 'extcommunity color matches-within <set | (inline)>', 'extcommunity color matches-within ${1:set}'],
  ['extcommunity color is-empty', 'true if route has no Color extended community'],
  ['extcommunity seg-nh matches-any', 'extcommunity seg-nh matches-any <set | (inline)>', 'extcommunity seg-nh matches-any ${1:set}'],
  ['extcommunity seg-nh matches-every', 'extcommunity seg-nh matches-every <set | (inline)>', 'extcommunity seg-nh matches-every ${1:set}'],
  ['extcommunity seg-nh matches-within', 'extcommunity seg-nh matches-within <set | (inline)>', 'extcommunity seg-nh matches-within ${1:set}'],
  ['extcommunity seg-nh is-empty', 'true if route has no Segmented-NH extended community'],
  ['extcommunity length', 'extcommunity length <eq|is|ge|le> <number>', 'extcommunity length ${1|eq,ge,le,is|} ${2:number}'],
  ['local-preference', 'local-preference <eq|is|ge|le> <number>', 'local-preference ${1|eq,ge,le,is|} ${2:number}'],
  ['med', 'med <eq|is|ge|le> <number>', 'med ${1|eq,ge,le,is|} ${2:number}'],
  ['aigp-metric', 'aigp-metric <eq|is|ge|le> <number>', 'aigp-metric ${1|eq,ge,le,is|} ${2:number}'],
  ['algorithm', 'algorithm <eq|is|ge|le> <0-255>', 'algorithm ${1|eq,ge,le,is|} ${2:number}'],
  ['label-index', 'label-index <eq|is|ge|le> <number>', 'label-index ${1|eq,ge,le,is|} ${2:number}'],
  ['rib-metric', 'rib-metric <eq|is|ge|le> <number> (table-policy)', 'rib-metric ${1|eq,ge,le,is|} ${2:number}'],
  ['next-hop in', 'next-hop in <prefix-set | (inline)>', 'next-hop in ${1:prefix-set}'],
  ['origin is', 'origin is <igp|egp|incomplete>', 'origin is ${1|igp,egp,incomplete|}'],
  ['orf prefix in', 'orf prefix in <prefix-set | (inline)>', 'orf prefix in ${1:prefix-set}'],
  ['ospf-area is', 'ospf-area is <0-4294967295 | A.B.C.D>', 'ospf-area is ${1:area}'],
  ['ospf-area in', 'ospf-area in <ospf-area-set | (inline)>', 'ospf-area in ${1:ospf-area-set}'],
  ['ospf-area all-paths', 'all paths match: ospf-area all-paths <is|in> ...', 'ospf-area all-paths ${1|is,in|} ${2:area}'],
  ['path-type is', 'path-type is <ibgp|ebgp>', 'path-type is ${1|ibgp,ebgp|}'],
  ['protocol is', 'protocol is <bgp|connected|eigrp|isis|ospf|ospfv3|rip|static>', 'protocol is ${1|bgp,connected,eigrp,isis,ospf,ospfv3,rip,static|}'],
  ['protocol in', 'protocol in (proto, proto, ...)', 'protocol in (${1:bgp})'],
  ['rd in', 'rd in <rd-set | (inline)>', 'rd in ${1:rd-set}'],
  ['rib-has-route in', 'true if RIB has a route in the prefix set', 'rib-has-route in ${1:prefix-set}'],
  ['rib-has-route async', 'async RIB lookup: rib-has-route async <prefix-set>', 'rib-has-route async ${1:prefix-set}'],
  ['route-has-label', 'true if route carries one or more MPLS labels'],
  ['route-has-vrf-ri', 'true if RIB route has VRF Route-Import extended community'],
  ['route-aggregated', 'true if route is aggregated'],
  ['aggregate-contributor', 'true if route contributes to an aggregate'],
  ['i-pmsi-present', 'true if BGP I-PMSI route is present'],
  ['route-type is', 'route-type is <interarea|internal|local|level-1|level-2|ospf-*|type-1|type-2>', 'route-type is ${1|interarea,internal,local,level-1,level-1-2,level-2,ospf-external-type-1,ospf-external-type-2,ospf-inter-area,ospf-intra-area,ospf-nssa-type-1,ospf-nssa-type-2,type-1,type-2|}'],
  ['source in', 'source in <prefix-set | (inline)> — route source/originator', 'source in ${1:prefix-set}'],
  ['tag', 'tag <eq|is|ge|le> <number>', 'tag ${1|eq,ge,le,is|} ${2:number}'],
  ['tag in', 'tag in <tag-set | (inline)>', 'tag in ${1:tag-set}'],
  ['track', 'track <name> is <up|down> — object tracking', 'track ${1:name} is ${2|up,down|}'],
  ['validation-state is', 'RPKI: validation-state is <valid|invalid|not-found>', 'validation-state is ${1|valid,invalid,not-found|}'],
  ['vpn-distinguisher is', 'vpn-distinguisher is <number>', 'vpn-distinguisher is ${1:number}'],
  ['esi in', 'EVPN: esi in <esi-set | (inline)>', 'esi in ${1:esi-set}'],
  ['etag in', 'EVPN: etag in <etag-set | (inline)>', 'etag in ${1:etag-set}'],
  ['mac in', 'EVPN: mac in <mac-set | (inline)>', 'mac in ${1:mac-set}'],
  ['evpn-gateway in', 'EVPN gateway IP in <prefix-set | (inline)>', 'evpn-gateway in ${1:prefix-set}'],
  ['evpn-originator in', 'EVPN originating router IP in <prefix-set | (inline)>', 'evpn-originator in ${1:prefix-set}'],
  ['evpn-route-type is', 'evpn-route-type is <1-8>', 'evpn-route-type is ${1:number}'],
  ['mldp flex-algo', 'mldp flex-algo <128-255 | any | none>', 'mldp flex-algo ${1:any}'],
  ['mldp opaque', 'mldp opaque <global-id|ipv4|ipv6|mdt|recursive|recursive-rd|static-id|vpnv4|vpnv6>', 'mldp opaque ${1|global-id,ipv4,ipv6,mdt,recursive,recursive-rd,static-id,vpnv4,vpnv6|}'],
  ['mldp root', 'mldp root <A.B.C.D | X:X::X | $param>', 'mldp root ${1:address}'],
  ['globalVar1', 'globalVar1 <eq|is|ge|le> <number> — set via var statement', 'globalVar1 ${1|eq,ge,le,is|} ${2:number}'],
  ['globalVar2', 'globalVar2 <eq|is|ge|le> <number> — set via var statement', 'globalVar2 ${1|eq,ge,le,is|} ${2:number}'],
  ['globalVar3', 'globalVar3 <eq|is|ge|le> <number> — set via var statement', 'globalVar3 ${1|eq,ge,le,is|} ${2:number}'],
  ['globalVar4', 'globalVar4 <eq|is|ge|le> <number> — set via var statement', 'globalVar4 ${1|eq,ge,le,is|} ${2:number}'],
  ['globalVar5', 'globalVar5 <eq|is|ge|le> <number> — set via var statement', 'globalVar5 ${1|eq,ge,le,is|} ${2:number}'],
  ['apply', 'apply <route-policy> as boolean condition', 'apply ${1:policy-name}'],
];

const SET_ATTRS = [
  ['administrative-distance', 'set administrative-distance <1-255>'],
  ['advertise-evpn-gw-ip', 'set advertise-evpn-gw-ip <A.B.C.D | X:X::X | use-next-hop>'],
  ['aggregate-contributor', 'set aggregate-contributor — mark route as aggregate contributor'],
  ['aigp-metric', 'set aigp-metric <number | +n | -n | igp-cost>'],
  ['algorithm', 'set algorithm <0-255>'],
  ['attribute-set', 'set attribute-set <TE attribute-set name>'],
  ['c-multicast-routing', 'set c-multicast-routing <bgp|pim>', 'c-multicast-routing ${1|bgp,pim|}'],
  ['community', 'set community <set | (inline)> [additive]', 'community ${1:community-set}${2: additive}'],
  ['core-tree', 'set core-tree <ingress-replication[-default|-partitioned]|mldp[-default|-inband|-partitioned-*]|p2mp-te[-default|-partitioned]|pim-default|sr-p2mp>'],
  ['dampening', 'set dampening halflife <1-45> reuse <n> suppress <n> max-suppress <min> | others', 'dampening halflife ${1:15} reuse ${2:750} suppress ${3:2000} max-suppress ${4:60}'],
  ['data-mdt', 'set data-mdt <name> — MVPN Data MDT'],
  ['downstream-core-tree', 'set downstream-core-tree <ingress-replication|mldp|p2mp-te|sr-p2mp>', 'downstream-core-tree ${1|ingress-replication,mldp,p2mp-te,sr-p2mp|}'],
  ['eigrp-metric', 'set eigrp-metric <bw-kbps> <delay-10us> <reliability> <loading> <mtu>'],
  ['encapsulation-type', 'set encapsulation-type mpls-udp'],
  ['entropy-label', 'set entropy-label bgp'],
  ['extcommunity rt', 'set extcommunity rt <set | (inline)> [additive]', 'extcommunity rt ${1:set}${2: additive}'],
  ['extcommunity soo', 'set extcommunity soo <set | (inline)> [additive]', 'extcommunity soo ${1:set}${2: additive}'],
  ['extcommunity cost', 'set extcommunity cost <set | (inline)>'],
  ['extcommunity bandwidth', 'set extcommunity bandwidth <set | (asn:bps)>'],
  ['extcommunity color', 'set extcommunity color <set | (inline)> [additive]', 'extcommunity color ${1:set}${2: additive}'],
  ['extcommunity evpn-link-bandwidth', 'set extcommunity evpn-link-bandwidth <(inline)>'],
  ['extcommunity redirect-to-rt', 'set extcommunity redirect-to-rt <(inline)> — flowspec redirect'],
  ['extcommunity seg-nh', 'set extcommunity seg-nh <set | (inline)> — P2MP segmented next-hop'],
  ['fallback-vrf-lookup', 'set fallback-vrf-lookup — enable fallback VRF lookup'],
  ['fast-reroute', 'set fast-reroute lfa — LFA fast-reroute protection'],
  ['flex-algo', 'set flex-algo <128-255 | none>'],
  ['flow-tag', 'set flow-tag <1-63>'],
  ['forward-class', 'set forward-class <1-7>'],
  ['ip-precedence', 'set ip-precedence <0-7>'],
  ['isis-metric', 'set isis-metric <0-16777215>'],
  ['label', 'set label <0-1048575 | explicit-null | implicit-null>'],
  ['label-index', 'set label-index <segment-routing index 0-1048575>'],
  ['label-mode', 'set label-mode <per-ce|per-vrf|per-prefix>', 'label-mode ${1|per-ce,per-vrf,per-prefix|}'],
  ['large-community', 'set large-community <set | (inline)> [additive]', 'large-community ${1:set}${2: additive}'],
  ['level', 'set level <level-1|level-2|level-1-2>', 'level ${1|level-1,level-2,level-1-2|}'],
  ['load-balance', 'set load-balance ecmp-consistent'],
  ['local-preference', 'set local-preference <number | +n | -n | *n>', 'local-preference ${1:100}'],
  ['locator-prefix', 'set locator-prefix — destination is SRv6 locator prefix'],
  ['lsm-root', 'set lsm-root <A.B.C.D> — label-switched multicast root'],
  ['maximum-paths', 'set maximum-paths <1-64> — max parallel paths per route'],
  ['med', 'set med <number | +n | -n | igp-cost | max-reachable>', 'med ${1:number}'],
  ['metric-type', 'set metric-type <type-1|type-2|internal|external|rib-metric-as-internal|rib-metric-as-external>', 'metric-type ${1|type-1,type-2,internal,external,rib-metric-as-internal,rib-metric-as-external|}'],
  ['mpls traffic-eng attributeset', 'set mpls traffic-eng attributeset <name>', 'mpls traffic-eng attributeset ${1:name}'],
  ['next-hop', 'set next-hop <A.B.C.D | X:X::X | self | peer-address | discard | ipv6-global | ipv6-linklocal | unchanged>', 'next-hop ${1:address}'],
  ['no-label-allocation', 'set no-label-allocation'],
  ['on-demand-color', 'set on-demand-color <0-4294967295> — SR ODN color'],
  ['origin', 'set origin <igp|egp|incomplete>', 'origin ${1|igp,egp,incomplete|}'],
  ['ospf-metric', 'set ospf-metric <0-4294967295>'],
  ['path-color', 'set path-color external-reach'],
  ['path-selection', 'set path-selection <all|backup 1|best-path|group-best|multipath> [install] [advertise] [multipath-protect]', 'path-selection ${1|all,backup 1,best-path,group-best,multipath|}'],
  ['qos-group', 'set qos-group <0-31>'],
  ['rib-metric', 'set rib-metric <0-4294967295> — table-policy'],
  ['rip-metric', 'set rip-metric <0-16>'],
  ['rip-tag', 'set rip-tag <0-65535>'],
  ['rpf-topology', 'set rpf-topology [vrf <name>] <ipv4|ipv6> <multicast|unicast> [topology <name>]'],
  ['rt-set route-limit', 'set rt-set route-limit <0-4294967295>'],
  ['s-pmsi', 'set s-pmsi star-g — (*,G) S-PMSI advertisement', 's-pmsi star-g'],
  ['sfi', 'set sfi <name>'],
  ['spf-priority', 'set spf-priority <critical|high|medium>', 'spf-priority ${1|critical,high,medium|}'],
  ['sr-policy-color', 'set sr-policy-color <0-4294967295>'],
  ['srv6 sid-format', 'set srv6 sid-format usid-f3216', 'srv6 sid-format usid-f3216'],
  ['srv6-alloc-mode', 'set srv6-alloc-mode <per-ce|per-vrf>', 'srv6-alloc-mode ${1|per-ce,per-vrf|}'],
  ['static-p2mp-te', 'set static-p2mp-te <tunnel-name>'],
  ['tag', 'set tag <0-4294967295>'],
  ['traffic-index', 'set traffic-index <1-63 | ignore>'],
  ['upstream-core-tree', 'set upstream-core-tree <ingress-replication|mldp|p2mp-te|sr-p2mp>', 'upstream-core-tree ${1|ingress-replication,mldp,p2mp-te,sr-p2mp|}'],
  ['vpn-distinguisher', 'set vpn-distinguisher <1-4294967295>'],
  ['weight', 'set weight <0-65535>'],
];

const STATEMENTS = [
  ['if', 'if <condition> then ... endif', 'if ${1:condition} then\n\t$0\nendif'],
  ['elseif', 'elseif <condition> then', 'elseif ${1:condition} then'],
  ['else', 'else branch'],
  ['endif', 'end of if block'],
  ['set', 'set <attribute> <value>'],
  ['add', 'add <eigrp-metric|rip-metric> <value> — add offset to existing value', 'add ${1|eigrp-metric,rip-metric|} ${2:value}'],
  ['var', 'var globalVar<1-5> <number | $param> — set attach-point scoped variable', 'var globalVar${1|1,2,3,4,5|} ${2:value}'],
  ['apply', 'apply <route-policy> [(param, ...)] — hierarchical policy', 'apply ${1:policy-name}'],
  ['pass', 'accept route, continue evaluating'],
  ['drop', 'reject route, stop'],
  ['done', 'accept route, stop'],
  ['abort', 'discard all policy modifications, reject'],
  ['delete community', 'delete community <in|not in> <set | (inline)> | all', 'delete community in ${1:community-set}'],
  ['delete extcommunity rt', 'delete extcommunity <rt|soo|color|seg-nh|bandwidth|evpn-link-bandwidth> <in|not in|all>', 'delete extcommunity rt in ${1:set}'],
  ['delete large-community', 'delete large-community <in|not in> <set | (inline)> | all', 'delete large-community in ${1:set}'],
  ['delete prefix-sid', 'delete prefix segment ID attribute'],
  ['prepend as-path', 'prepend as-path <asn | most-recent | own-as> [count]', 'prepend as-path ${1:asn} ${2:count}'],
  ['replace as-path', "replace as-path <'asn ...' | all [auto|none|'...'] [count] | private-as>", 'replace as-path ${1:private-as}'],
  ['remove as-path private-as', 'strip private AS numbers from path'],
  ['suppress-route', 'suppress component route of an aggregate'],
  ['unsuppress-route', 'unsuppress previously suppressed route'],
  ['end-policy', 'end of route-policy definition'],
];

const TOPLEVEL = [
  ['route-policy', 'route-policy <name> [($param, ...)]', 'route-policy ${1:name}\n\t$0\nend-policy'],
  ['prefix-set', 'prefix-set <name>', 'prefix-set ${1:name}\n\t${2:10.0.0.0/8 le 24}\nend-set'],
  ['as-path-set', 'as-path-set <name>', "as-path-set ${1:name}\n\tios-regex '${2:_65000\\$}'\nend-set"],
  ['community-set', 'community-set <name>', 'community-set ${1:name}\n\t${2:65000:100}\nend-set'],
  ['large-community-set', 'large-community-set <name>', 'large-community-set ${1:name}\n\t${2:65000:1:100}\nend-set'],
  ['extcommunity-set rt', 'extcommunity-set rt <name>', 'extcommunity-set rt ${1:name}\n\t${2:65000:100}\nend-set'],
  ['extcommunity-set soo', 'extcommunity-set soo <name>', 'extcommunity-set soo ${1:name}\n\t${2:65000:100}\nend-set'],
  ['extcommunity-set cost', 'extcommunity-set cost <name>'],
  ['extcommunity-set bandwidth', 'extcommunity-set bandwidth <name>'],
  ['extcommunity-set opaque', 'extcommunity-set opaque <name> — MLDP opaque'],
  ['extcommunity-set evpn-link-bandwidth', 'extcommunity-set evpn-link-bandwidth <name>'],
  ['extcommunity-set seg-nh', 'extcommunity-set seg-nh <name> — P2MP segmented next-hop'],
  ['rd-set', 'rd-set <name>', 'rd-set ${1:name}\n\t${2:65000:*}\nend-set'],
  ['tag-set', 'tag-set <name>', 'tag-set ${1:name}\n\t${2:100}\nend-set'],
  ['esi-set', 'esi-set <name> — EVPN Ethernet segment IDs', 'esi-set ${1:name}\n\t${2:0011.2222.3333.4444.5555}\nend-set'],
  ['etag-set', 'etag-set <name> — EVPN Ethernet tags', 'etag-set ${1:name}\n\t${2:100}\nend-set'],
  ['mac-set', 'mac-set <name>', 'mac-set ${1:name}\n\t${2:1122.3344.5566}\nend-set'],
  ['ospf-area-set', 'ospf-area-set <name>', 'ospf-area-set ${1:name}\n\t${2:0}\nend-set'],
  ['policy-global', 'policy-global — systemwide $variables', "policy-global\n\t${1:name} '${2:value}'\nend-global"],
];

const CORE_TREE_TYPES = ['ingress-replication', 'ingress-replication-default', 'ingress-replication-partitioned',
  'mldp', 'mldp-default', 'mldp-inband', 'mldp-partitioned-mp2mp', 'mldp-partitioned-p2mp',
  'p2mp-te', 'p2mp-te-default', 'p2mp-te-partitioned', 'pim-default', 'sr-p2mp'];

const ENUM_AFTER = [
  // [regex on line prefix, completions] — first match wins, so specific before generic.

  // set path-selection <mode> [install] [advertise] [multipath-protect]
  [/\bset\s+path-selection\s+backup\s+\S+(?:\s+[\w-]+)*\s+[\w-]*$/, ['install', 'advertise', 'multipath-protect']],
  [/\bset\s+path-selection\s+backup\s+\w*$/, ['1']],
  [/\bset\s+path-selection\s+multipath\s+advertise\s+[\w-]*$/, ['multipath-protect']],
  [/\bset\s+path-selection\s+(?:all|group-best|multipath)\s+[\w-]*$/, ['advertise']],
  [/\bset\s+path-selection\s+[\w-]*$/, ['all', 'backup', 'best-path', 'group-best', 'multipath']],

  // delete ...
  [/\bdelete\s+extcommunity\s+(?:rt|soo|color|seg-nh|bandwidth|evpn-link-bandwidth)\s+\w*$/, ['in', 'not in', 'all']],
  [/\bdelete\s+extcommunity\s+[\w-]*$/, ['bandwidth', 'color', 'evpn-link-bandwidth', 'rt', 'seg-nh', 'soo']],
  [/\bdelete\s+(?:community|large-community)\s+\w*$/, ['in', 'not in', 'all']],
  [/\bdelete\s+[\w-]*$/, ['community', 'extcommunity', 'large-community', 'prefix-sid']],

  // additive after a set value (named set or inline)
  [/\bset\s+(?:community|large-community|extcommunity\s+(?:rt|soo|color|bandwidth|evpn-link-bandwidth|seg-nh))\s+(?:\([^)]*\)|[$\w.:-]+)\s+\w*$/, ['additive']],

  // set extcommunity subtypes; set community/large-community take set names (see NAME_CTX), no enum
  [/\bset\s+extcommunity\s+[\w-]*$/, ['bandwidth', 'color', 'cost', 'evpn-link-bandwidth', 'redirect-to-rt', 'rt', 'seg-nh', 'soo']],
  [/\bset\s+(?:community|large-community|extcommunity\s+[\w-]+)\s+[($\w.:-]*$/, []],

  // set <attr> value enums
  [/\bset\s+advertise-evpn-gw-ip\s+[\w-]*$/, ['use-next-hop']],
  [/\bset\s+aigp-metric\s+[\w-]*$/, ['igp-cost']],
  [/\bset\s+c-multicast-routing\s+\w*$/, ['bgp', 'pim']],
  [/\bset\s+core-tree\s+[\w-]*$/, CORE_TREE_TYPES],
  [/\bset\s+(?:downstream|upstream)-core-tree\s+[\w-]*$/, ['ingress-replication', 'mldp', 'p2mp-te', 'sr-p2mp']],
  [/\bset\s+dampening\s+(?:[\w-]+\s+\d+\s+)*\w*$/, ['halflife', 'max-suppress', 'others', 'reuse', 'suppress']],
  [/\bset\s+encapsulation-type\s+[\w-]*$/, ['mpls-udp']],
  [/\bset\s+entropy-label\s+\w*$/, ['bgp']],
  [/\bset\s+fast-reroute\s+\w*$/, ['lfa']],
  [/\bset\s+flex-algo\s+\w*$/, ['none']],
  [/\bset\s+label\s+[\w-]*$/, ['explicit-null', 'implicit-null']],
  [/\bset\s+label-mode\s+[\w-]*$/, ['per-ce', 'per-vrf', 'per-prefix']],
  [/\bset\s+level\s+[\w-]*$/, ['level-1', 'level-2', 'level-1-2']],
  [/\bset\s+load-balance\s+[\w-]*$/, ['ecmp-consistent']],
  [/\bset\s+med\s+[\w-]*$/, ['igp-cost', 'max-reachable']],
  [/\bset\s+metric-type\s+[\w-]*$/, ['external', 'internal', 'rib-metric-as-external', 'rib-metric-as-internal', 'type-1', 'type-2']],
  [/\bset\s+mpls\s+traffic-eng\s+\w*$/, ['attributeset']],
  [/\bset\s+mpls\s+[\w-]*$/, ['traffic-eng']],
  [/\bset\s+next-hop\s+[\w-]*$/, ['self', 'peer-address', 'discard', 'ipv6-global', 'ipv6-linklocal', 'unchanged']],
  [/\bset\s+path-color\s+[\w-]*$/, ['external-reach']],
  [/\bset\s+rpf-topology\s+(?:vrf\s+\S+\s+)?(?:ipv4|ipv6)\s+\w*$/, ['multicast', 'unicast']],
  [/\bset\s+rpf-topology\s+\w*$/, ['ipv4', 'ipv6', 'vrf']],
  [/\bset\s+rt-set\s+[\w-]*$/, ['route-limit']],
  [/\bset\s+s-pmsi\s+[\w-]*$/, ['star-g']],
  [/\bset\s+spf-priority\s+\w*$/, ['critical', 'high', 'medium']],
  [/\bset\s+srv6\s+sid-format\s+[\w-]*$/, ['usid-f3216']],
  [/\bset\s+srv6\s+[\w-]*$/, ['sid-format']],
  [/\bset\s+srv6-alloc-mode\s+[\w-]*$/, ['per-ce', 'per-vrf']],
  [/\bset\s+traffic-index\s+\w*$/, ['ignore']],

  // statements
  [/\badd\s+[\w-]*$/, ['eigrp-metric', 'rip-metric']],
  [/\bvar\s+\w*$/, ['globalVar1', 'globalVar2', 'globalVar3', 'globalVar4', 'globalVar5']],
  [/\bprepend\s+as-path\s+[\w-]*$/, ['most-recent', 'own-as']],
  [/\breplace\s+as-path\s+all\s+[\w-]*$/, ['auto', 'none']],
  [/\breplace\s+as-path\s+[\w-]*$/, ['all', 'private-as']],
  [/\b(?:prepend|replace)\s+\w*$/, ['as-path']],
  [/\bremove\s+[\w-]*$/, ['as-path private-as']],

  // shared / condition-side enums
  [/\b(?:set\s+)?origin\s+(?:is\s+)?\w*$/, ['igp', 'egp', 'incomplete']],
  [/\bpath-type\s+is\s+\w*$/, ['ibgp', 'ebgp']],
  [/\bvalidation-state\s+is\s+[\w-]*$/, ['valid', 'invalid', 'not-found']],
  [/\bprotocol\s+(?:is\s+|in\s+\(\s*)\w*$/, ['bgp', 'connected', 'eigrp', 'isis', 'ospf', 'ospfv3', 'rip', 'static']],
  [/\bprotocol\s+\w*$/, ['is', 'in']],
  [/\bevpn-route-type\s+is\s+\w*$/, ['1', '2', '3', '4', '5', '6', '7', '8']],
  [/\bevpn-route-type\s+\w*$/, ['is']],
  [/\broute-type\s+is\s+[\w-]*$/, ['interarea', 'internal', 'local', 'level-1', 'level-1-2', 'level-2',
    'ospf-external-type-1', 'ospf-external-type-2', 'ospf-inter-area', 'ospf-intra-area',
    'ospf-nssa-type-1', 'ospf-nssa-type-2', 'type-1', 'type-2']],
  [/\bdestination\s+[\w-]*$/, ['in', 'is-all', 'is-backup-path', 'is-best-external', 'is-best-path',
    'is-multi-path', 'is-multipath-protect', 'longer-than', 'or-longer']],
  [/\bmldp\s+opaque\s+[\w-]*$/, ['global-id', 'ipv4', 'ipv6', 'mdt', 'recursive', 'recursive-rd', 'static-id', 'vpnv4', 'vpnv6']],
  [/\bmldp\s+flex-algo\s+\w*$/, ['any', 'none']],
  [/\bmldp\s+[\w-]*$/, ['flex-algo', 'opaque', 'root']],
  [/\bospf-area\s+all-paths\s+\w*$/, ['is', 'in']],
  [/\bospf-area\s+[\w-]*$/, ['all-paths', 'in', 'is']],
  [/\brib-has-route\s+\w*$/, ['async', 'in']],
  [/\btrack\s+\S+\s+is\s+\w*$/, ['up', 'down']],
  [/\btrack\s+\S+\s+\w*$/, ['is']],

  // comparators — not after `set` (there the attribute takes a value, not an operator)
  [/(?<!\bset\s)(?:\b(?:med|local-preference|aigp-metric|algorithm|label-index|rib-metric|globalVar\d)|\bas-path\s+(?:length|unique-length)|\b(?:community|extcommunity|large-community)\s+length)\s+\w*$/, ['eq', 'ge', 'le', 'is']],
  [/(?<!\bset\s)(?<![\w-])tag\s+\w*$/, ['eq', 'ge', 'in', 'is', 'le']],

  // operator lists per attribute (if-context; set-context matched earlier)
  [/\bas-path\s+[\w-]*$/, ['in', 'is-local', 'length', 'unique-length', 'neighbor-is', 'originates-from', 'passes-through']],
  [/\bextcommunity\s+rt\s+[\w-]*$/, ['in', 'matches-any', 'matches-every', 'matches-within', 'is-empty']],
  [/\bextcommunity\s+(?:soo|color|seg-nh)\s+[\w-]*$/, ['matches-any', 'matches-every', 'matches-within', 'is-empty']],
  [/\bextcommunity\s+[\w-]*$/, ['color', 'length', 'rt', 'seg-nh', 'soo']],
  [/\blarge-community\s+[\w-]*$/, ['is-empty', 'length', 'matches-any', 'matches-every', 'matches-within']],
  [/\bcommunity\s+[\w-]*$/, ['in', 'is-empty', 'length', 'matches-any', 'matches-every', 'matches-within']],
];

// Condition context: after if/elseif or a boolean operator.
const CONDITION_CTX = /\b(?:if|elseif|and|or|not)\s+(?:\(\s*)?[\w-]*$|\(\s*[\w-]*$/;

// Returns [{label, detail?, snippet?}] for a given line prefix.
function complete(linePrefix) {
  const items = (list) => list.map(([label, detail, snippet]) => ({ label, detail, snippet }));
  const words = (list) => list.map((w) => ({ label: w }));

  for (const [re, values] of ENUM_AFTER) {
    if (re.test(linePrefix)) return words(values);
  }
  if (/\bset\s+[\w-]*$/.test(linePrefix)) return items(SET_ATTRS);
  if (CONDITION_CTX.test(linePrefix)) return items(CONDITIONS);
  if (/^\s*[\w-]*$/.test(linePrefix)) return items(STATEMENTS).concat(items(TOPLEVEL));
  return [];
}

module.exports = { CONDITIONS, SET_ATTRS, STATEMENTS, TOPLEVEL, ENUM_AFTER, complete };
